### ISSUE TITLE
Extract I, Q, and U from raw Mk4 files

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/mk4-pipeline#1]
Current plan:

- [x] write an IDL routine to change byte order of 16-bit integers and write output with a new name
- [x] run original `rawt4.c` code on the modified data files

This should output `.I`, `.Q`, `.U`, `.ST`, and `.SK` files.

**Comment by mgalloy** [comment]
My modified code outputted the following:

    mk4$ rawt4v2 /home/cordyn/src/mk4v2/MIKE_MK4DATA/2012_07_26_c18_09.rawmk4.swapped
    
    Reading /home/cordyn/src/mk4v2/MIKE_MK4DATA/2012_07_26_c18_09.rawmk4.swapped
    recno = 2
    Reading record no 0
    j > 0
    Wrong size read record 0 34 bytes
    swapped recno = 12594
    recno changed to 12849
    end of if, i=0
    end of iteration, i=0, recno=12849
    Reading record no 1
        Number of records --> 1
         SkyTx : 12133.000
    Never found the correct InsDesc

**Comment by mgalloy** [comment]
Whoops, had a typo in the IDL code to convert the endianness. New output loops through the 983 records and ends with:

    Number of records --> 983
             SkyTx : 2432.000
            Writing 12d208.18_09.mk4.i
            
            Writing 12d208.18_09.mk4.q
            
            Writing 12d208.18_09.mk4.u
            
                SkyTx  = 2432.00
                pangle =    8.83
            Writing 12d208.18_09.mk4.sk
            
            Writing 12d208.18_09.mk4.ba
            
            Writing 12d208.18_09.mk4.st

And also created the following files in the current working directory:

    mk4$ ll 12d208*
    -rw-rw-r--. 1 mgalloy cordyn 3.0K Jun 21 14:43 12d208.18_09.mk4.ba
    -rw-rw-r--. 1 mgalloy cordyn 739K Jun 21 14:43 12d208.18_09.mk4.i
    -rw-rw-r--. 1 mgalloy cordyn 739K Jun 21 14:43 12d208.18_09.mk4.q
    -rw-rw-r--. 1 mgalloy cordyn 3.0K Jun 21 14:43 12d208.18_09.mk4.sk
    -rw-rw-r--. 1 mgalloy cordyn 3.0K Jun 21 14:43 12d208.18_09.mk4.st
    -rw-rw-r--. 1 mgalloy cordyn 739K Jun 21 14:43 12d208.18_09.mk4.u

**Comment by jburkepile** [comment]
On Aug 11, 2023 Alice sent us this info. She created a new directory with updated mk4 code to produce .q and .rq images from the rawmk4 files:

> Hi Joan and Mike,
>
> I've created a new directory that just has the new code in it to produce the ".rq" data from the ".rawmk4" files.
>
> This new directory is:
>
>     /home/alice/mk4v2_2023
>
> To create the .i .q .u .ba files, use:
>
>     /home/alice/mk4v2_2023/rawt4v2 2012_07_26_23_56.rawmk4
>
> To create the .rq files, use:
>
>     /home/alice/mk4v2_2023/cy2rec4        -sf  *.q
>
> The `-sf` flag will do a 'sign flip' if it notices that that sign of the diode signal was flipped in the raw data.
>
> The data is on:
>
>     [bonito.hao.ucar.edu](http://bonito.hao.ucar.edu/)
>
> And in:
>
>     /export/data1/alice/mk4/20120726
>
> Please see the "dome.csh" file for how I use rawt4v2 and cy2rec4
